spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: toor
    url: jdbc:mysql://localhost:3306/techxp
    username: root
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create
    show-sql: true
app:
  secret: ochhane